const team_colors = {'Alliance': "#278e4a",
 'CDEC Gaming': "#cd2026",
 'Chaos Esports Club': "#2c265e",
 'Cloud9': "#27a1db",
 'Complexity Gaming': "#002a5c",
 'EHOME': "#8f1210",
 'Evil Geniuses': "#224a88",
 'Fnatic': "#f19f3f",
 'HellRaisers': "#cb0f0a",
 'Infamous': "#ac120d", 
 'Invictus Gaming': "#060606",
 'IG Vitality': "#060606",
 'Kaipi': "#ec8a29",
 'Keen Gaming': "#7b4e94",
 'LGD.Forever Young': "#cb292c",
 'MVP HOT6ix': "#2b659d",
 'MVP Phoenix': "#2b659d",
 'Meet Your Makers': "#59b0ce",
 'MiTH': "#fdfa64",
 'Mineski': "#a6a6a7",
 'Moscow Five': "#c11b21",
 'Mousesports': "#af1c3b",
 'Natus Vincere': "#fef536",
 'Newbee': "#2683c5",
 'Newbee Young': "#2683c5",
 'Ninjas in Pyjamas': "#a78b65",
 'No Tidehunter': "#86dd7f",
 'OG': "#022554",
 'OpTic Gaming': "#9ac94b",
 'Orange Esports': "#f08230",
 'Power Rangers': "#6e0306",
 'PSG.LGD': "#cb292c",
 'PaiN Gaming': "#2a2e38",
 'Rave': "#426a96",
 'Scythe Gaming': "#edb629",
 'TNC Predator': "#f26b2f",
 'Team DK': "#86acba",
 'Team Empire': "#ec1c24",
 'Team Liquid': "#6eaed9",
 'Team Secret': "#000000",
 'Team Spirit': "#bdf935",
 'TongFu': "#efbb48",
 'Vega Squadron': "#0083e7", 
 'VGJ.Storm': "#4c8dcb",
 'VGJ.Thunder': "#4c8dcb",
 'Vici Gaming': "#888888",
 'Vici Gaming Reborn': "#888888",
 'Virtus.pro': "#fd5417",
 'Wings Gaming': "#d8d9d9",
}


const teamLogos = [
{"team_name":"OG","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/b\\/bc\\/OG_RB_logo_std.png"},
{"team_name":"Team Liquid","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/c\\/cd\\/Liquid2017logo_std.png"},
{"team_name":"Evil Geniuses","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/8d\\/Evil_Geniuses_2018_updated_std.png"},
{"team_name":"Newbee","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/b\\/b9\\/Newbeelogo_std.png"},
{"team_name":"Team Secret","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/a\\/a7\\/Secretdotalogo_std.png"},
{"team_name":"Wings Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/6\\/66\\/Wingslogo_std.png"},
{"team_name":"Virtus.pro","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/8e\\/Virtus.pro_2019_std.png"},
{"team_name":"PSG.LGD","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/6\\/61\\/PSG.LGD_logo_std.png"},
{"team_name":"Vici Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/a\\/ad\\/Vglogo_std.png"},
{"team_name":"Natus Vincere","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/b\\/bb\\/Navilogo_std.png"},
{"team_name":"Fnatic","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/4\\/48\\/Fnaticlogo_std.png"},
{"team_name":"Invictus Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/a\\/a8\\/IGlogo_std.png"},
{"team_name":"EHOME","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/3\\/3b\\/Ehomelogo_std.png"},
{"team_name":"Alliance","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/6\\/6b\\/Alliancelogo2016_std.png"},
{"team_name":"TNC Predator","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/85\\/TNC_Predator_logo_std_201907.png"},
{"team_name":"Mineski","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/2\\/2a\\/Mineski_logo_06-2017_std.png"},
{"team_name":"MVP Phoenix","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/0\\/02\\/MVPPhoenixlogo_std.png"},
{"team_name":"Team Empire","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/1\\/11\\/Empirelogo_std.png"},
{"team_name":"Infamous","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/4\\/45\\/Infamous_logo_2017_std.png"},
{"team_name":"Team DK","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/2\\/22\\/DKlogo_std.png"},
{"team_name":"Cloud9","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/e\\/e7\\/C9logo_std.png"},
{"team_name":"Keen Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/0\\/0d\\/Keen_Gaming_logo_std.png"},
{"team_name":"Ninjas in Pyjamas","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/e\\/e9\\/NiP-StarLogo_2017-Black_std.png"},
{"team_name":"Complexity Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/a\\/a7\\/Complexity_Gaming_2019_std.png"},
{"team_name":"VGJ.Thunder","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/81\\/VGJ_Thunder_logo_std.png"},
{"team_name":"CDEC Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/6\\/6e\\/Cdeclogo_std.png"},
{"team_name":"Vega Squadron","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/5\\/5d\\/Vega2016logo_std.png"},
{"team_name":"OpTic Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/b\\/b0\\/OpTic_Gaminglogo_std.png"},
{"team_name":"TongFu","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/c\\/c6\\/Tongfulogo_std.png"},
{"team_name":"Orange Esports","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/9\\/91\\/Orangelogo_std.png"},
{"team_name":"LGD.Forever Young","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/4\\/4e\\/LGD.FY_std.png"},
{"team_name":"Mousesports","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/d\\/dc\\/Mousesportslogo_std.png"},
{"team_name":"Execration","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/1\\/17\\/Execrationlogo_std.png"},
{"team_name":"PaiN Gaming","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/6\\/68\\/Pain2017logo_std.png"},
{"team_name":"IG Vitality","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/7\\/76\\/IGVlogo_std.png"},
{"team_name":"Team Spirit","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/87\\/Team_Spirit_2016logo_std.png"},
{"team_name":"No Tidehunter","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/5\\/5b\\/No_Tidehunter.png"},
{"team_name":"HellRaisers","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/7\\/71\\/Hellraiserslogo_std.png"},
{"team_name":"Rave","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/4\\/48\\/Ravelogo_std.png"},
{"team_name":"MVP HOT6ix","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/85\\/MVPHOT6ixlogo_std.png"},
{"team_name":"Kaipi","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/9\\/9d\\/Kaipilogo_std.png"},
{"team_name":"Moscow Five","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/6\\/64\\/M5logo_std.png"},
{"team_name":"RoX","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/0\\/00\\/Roxlogo_std.png"},
{"team_name":"Power Rangers","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/4\\/42\\/Prlogo_std.png"},
{"team_name":"Team Dignitas","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/f\\/fb\\/Dignitaslogo_std.png"},
{"team_name":"MiTH","team_logo_url":"https:\\/\\/liquipedia.net\\/commons\\/images\\/8\\/88\\/MiTHlogo_std.png"}]
