const team_colors = {'Alliance': "#278e4a",
 'CDEC Gaming': "#cd2026",
 'Chaos Esports Club': "#2c265e",
 'Cloud9': "#27a1db",
 'Complexity Gaming': "#002a5c",
 'EHOME': "#8f1210",
 'Evil Geniuses': "#224a88",
 'Fnatic': "#f19f3f",
 'HellRaisers': "#cb0f0a",
 'Infamous': "#ac120d", 
 'Invictus Gaming': "#060606",
 'IG Vitality': "#060606",
 'Kaipi': "#ec8a29",
 'Keen Gaming': "#7b4e94",
 'LGD.Forever Young': "#cb292c",
 'MVP HOT6ix': "#2b659d",
 'MVP Phoenix': "#2b659d",
 'Meet Your Makers': "#59b0ce",
 'MiTH': "#fdfa64",
 'Mineski': "#a6a6a7",
 'Moscow Five': "#c11b21",
 'Mousesports': "#af1c3b",
 'Natus Vincere': "#fef536",
 'Newbee': "#2683c5",
 'Newbee Young': "#2683c5",
 'Ninjas in Pyjamas': "#a78b65",
 'No Tidehunter': "#86dd7f",
 'OG': "#022554",
 'OpTic Gaming': "#9ac94b",
 'Orange Esports': "#f08230",
 'Power Rangers': "#6e0306",
 'PSG.LGD': "#cb292c",
 'PaiN Gaming': "#2a2e38",
 'Rave': "#426a96",
 'Scythe Gaming': "#edb629",
 'TNC Predator': "#f26b2f",
 'Team DK': "#86acba",
 'Team Empire': "#ec1c24",
 'Team Liquid': "#6eaed9",
 'Team Secret': "#000000",
 'Team Spirit': "#bdf935",
 'TongFu': "#efbb48",
 'Vega Squadron': "#0083e7", 
 'VGJ.Storm': "#4c8dcb",
 'VGJ.Thunder': "#4c8dcb",
 'Vici Gaming': "#888888",
 'Vici Gaming Reborn': "#888888",
 'Virtus.pro': "#fd5417",
 'Wings Gaming': "#d8d9d9",
}


const teamLogos = [
{"team_name":"OG","team_logo_url":"imgs/OG_RB_logo_std.png"},
{"team_name":"Team Liquid","team_logo_url":"imgs/Liquid2017logo_std.png"},
{"team_name":"Evil Geniuses","team_logo_url":"imgs/Evil_Geniuses_2018_updated_std.png"},
{"team_name":"Newbee","team_logo_url":"imgs/Newbeelogo_std.png"},
{"team_name":"Team Secret","team_logo_url":"imgs/Secretdotalogo_std.png"},
{"team_name":"Wings Gaming","team_logo_url":"imgs/Wingslogo_std.png"},
{"team_name":"Virtus.pro","team_logo_url":"imgs/Virtus.pro_2019_std.png"},
{"team_name":"PSG.LGD","team_logo_url":"imgs/PSG.LGD_logo_std.png"},
{"team_name":"Vici Gaming","team_logo_url":"imgs/Vglogo_std.png"},
{"team_name":"Natus Vincere","team_logo_url":"imgs/Navilogo_std.png"},
{"team_name":"Fnatic","team_logo_url":"imgs/Fnaticlogo_std.png"},
{"team_name":"Invictus Gaming","team_logo_url":"imgs/IGlogo_std.png"},
{"team_name":"EHOME","team_logo_url":"imgs/Ehomelogo_std.png"},
{"team_name":"Alliance","team_logo_url":"imgs/Alliancelogo2016_std.png"},
{"team_name":"TNC Predator","team_logo_url":"imgs/TNC_Predator_logo_std_201907.png"},
{"team_name":"Mineski","team_logo_url":"imgs/Mineski_logo_06-2017_std.png"},
{"team_name":"MVP Phoenix","team_logo_url":"imgs/MVPPhoenixlogo_std.png"},
{"team_name":"Team Empire","team_logo_url":"imgs/Empirelogo_std.png"},
{"team_name":"Infamous","team_logo_url":"imgs/Infamous_logo_2017_std.png"},
{"team_name":"Team DK","team_logo_url":"imgs/DKlogo_std.png"},
{"team_name":"Cloud9","team_logo_url":"imgs/C9logo_std.png"},
{"team_name":"Keen Gaming","team_logo_url":"imgs/Keen_Gaming_logo_std.png"},
{"team_name":"Ninjas in Pyjamas","team_logo_url":"imgs/NiP-StarLogo_2017-Black_std.png"},
{"team_name":"Complexity Gaming","team_logo_url":"imgs/Complexity_Gaming_2019_std.png"},
{"team_name":"VGJ.Thunder","team_logo_url":"imgs/VGJ_Thunder_logo_std.png"},
{"team_name":"CDEC Gaming","team_logo_url":"imgs/Cdeclogo_std.png"},
{"team_name":"Vega Squadron","team_logo_url":"imgs/Vega2016logo_std.png"},
{"team_name":"OpTic Gaming","team_logo_url":"imgs/OpTic_Gaminglogo_std.png"},
{"team_name":"TongFu","team_logo_url":"imgs/Tongfulogo_std.png"},
{"team_name":"Orange Esports","team_logo_url":"imgs/Orangelogo_std.png"},
{"team_name":"LGD.Forever Young","team_logo_url":"imgs/LGD.FY_std.png"},
{"team_name":"Mousesports","team_logo_url":"imgs/Mousesportslogo_std.png"},
{"team_name":"Execration","team_logo_url":"imgs/Execrationlogo_std.png"},
{"team_name":"PaiN Gaming","team_logo_url":"imgs/Pain2017logo_std.png"},
{"team_name":"IG Vitality","team_logo_url":"imgs/IGVlogo_std.png"},
{"team_name":"Team Spirit","team_logo_url":"imgs/Team_Spirit_2016logo_std.png"},
{"team_name":"No Tidehunter","team_logo_url":"imgs/No_Tidehunter.png"},
{"team_name":"HellRaisers","team_logo_url":"imgs/Hellraiserslogo_std.png"},
{"team_name":"Rave","team_logo_url":"imgs/Ravelogo_std.png"},
{"team_name":"MVP HOT6ix","team_logo_url":"imgs/MVPHOT6ixlogo_std.png"},
{"team_name":"Kaipi","team_logo_url":"imgs/Kaipilogo_std.png"},
{"team_name":"Moscow Five","team_logo_url":"imgs/M5logo_std.png"},
{"team_name":"RoX","team_logo_url":"imgs/Roxlogo_std.png"},
{"team_name":"Power Rangers","team_logo_url":"imgs/Prlogo_std.png"},
{"team_name":"Team Dignitas","team_logo_url":"imgs/Dignitaslogo_std.png"},
{"team_name":"MiTH","team_logo_url":"imgs/MiTHlogo_std.png"}]
